default:
	pdflatex PDFLattice2017
	pdflatex PDFLattice2017
	bibtex PDFLattice2017
	pdflatex PDFLattice2017
	pdflatex PDFLattice2017	

clean:
	rm -rf *.bbl *~ *.out *.toc *.log PDFLattice2017.pdf *.aux *.blg *.pdf
